// Import environment variables from Vite
const BASE_URL = import.meta.env.VITE_API_BASE_URL;
const LOGIN_ENDPOINT = import.meta.env.VITE_LOGIN_ENDPOINT;
const GETUSERS_ENDPOINT = import.meta.env.VITE_ALLUSERS_ENDPOINT;
const USER_ENDPOINT = import.meta.env.VITE_USER_ENDPOINT;
const LOGOUT = import.meta.env.VITE_FETCH_DATA_ENDPOINT;
const WEBSOCKET_ENDPOINT = import.meta.env.VITE_WEBSOCKET_ENDPOINT;
const REFRESH_TOKEN_ENDPOINT = import.meta.env.VITE_REFRESHTOKEN_ENDPOINT;
const COURSES_ENDPOINT = import.meta.env.VITE_COURSES_ENDPOINT;
const COHORT_ENDPOINT = import.meta.env.VITE_COHORT_ENDPOINT

const endpoints = {
  LOGIN: `${BASE_URL}${LOGIN_ENDPOINT}`,
  USER: `${BASE_URL}${USER_ENDPOINT}`,
  GET_USERS: `${BASE_URL}${GETUSERS_ENDPOINT}`,
  LOGOUT: `${BASE_URL}${LOGOUT}`,
  REFRESH_TOKEN: `${BASE_URL}${REFRESH_TOKEN_ENDPOINT}`,
  WEBSOCKET_ENDPOINT: WEBSOCKET_ENDPOINT,
  COURSES: `${BASE_URL}${COURSES_ENDPOINT}`,
  COHORT: `${BASE_URL}${COHORT_ENDPOINT}`,

};

export {endpoints};
